FORMAT: 1A
HOST: https://api.businessbox.hu/

# BBox API dokumentáció

A dokumentáció a jelenleg API- keresztül elérhető BBox rendszerfunkciókat tartalmazza.

# SalesAPI Root [/vasarloigondoskodas/]
    
# Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "questions_url": "/questions"
        }

